name: 'Setup Kubernetes Tools'
description: 'Setup Kubernetes tools: kubectl, kustomize, helm, kubeconform, conftest, yq, rancher, tilt, skaffold, kube-score'
author: 'Yoichi Kawasaki @yokawasa'
inputs:
  fail-fast:
    required: false
    default: 'true'
    description: 'the action immediately fails when it fails to download (ie. due to a bad version)'
  setup-tools:
    required: false
    default: ''
    description: 'List of tool name to setup. By default, the action download and setup all supported Kubernetes tools. By specifying "setup-tools" you can choose which tools the action setup. Supported separator is return in multi-line string. Supported tools are "kubectl", "kustomize", "helm", "helmv3", "kubeval", "conftest", "yq", "rancher", "tilt", "skaffold", "kube-score"'
  kubectl:
    required: false
    default: '1.20.2'
    description: 'kubectl version'
  kustomize:
    required: false
    default: '4.0.5'
    description: 'kustomize version'
  helm:
    required: false
    default: '3.6.3'
    description: 'helm v3 version'
  helmv2:
    required: false
    default: '2.17.0'
    description: 'helm v2 version'
  kubeval:
    required: false
    default: '0.16.1'
    description: 'kubeval version'
  kubeconform:
    required: false
    default: '0.5.0'
    description: 'kubeconform version'
  conftest:
    required: false
    default: '0.19.0'
    description: 'conftest version'
  yq:
    required: false
    default: '4.7.1'
    description: 'yq version'
  rancher:
    required: false
    default: '2.4.10'
    description: 'rancher cli version'
  tilt:
    required: false
    default: '0.18.11'
    description: 'tilt version'
  skaffold:
    required: false
    default: '1.20.0'
    description: 'skaffold version'
  kube-score:
    required: false
    default: '1.10.1'
    description: 'kube-score version'
outputs:
  kubectl-path:
    description: 'kubectl command path if the action setup the tool, otherwise empty string'
  kustomize-path:
    description: 'kustomize command path if the action setup the tool, otherwise empty string'
  helm-path:
    description: 'helm command path if the action setup the tool, otherwise empty string'
  helmv2-path:
    description: 'helmv2 command path if the action setup the tool, otherwise empty string'
  kubeval-path:
    description: 'kubeval command path if the action setup the tool, otherwise empty string'
  conftest-path:
    description: 'conftest command path if the action setup the tool, otherwise empty string'
  yq-path:
    description: 'yq command path if the action setup the tool, otherwise empty string'
  rancher-path:
    description: 'rancher cli command path if the action setup the tool, otherwise empty string'
  tilt-path:
    description: 'tilt command path if the action setup the tool, otherwise empty string'
  skaffold-path:
    description: 'skaffold command path if the action setup the tool, otherwise empty string'
  kube-score-path:
    description: 'kube-score command path if the action setup the tool, otherwise empty string'
branding:
  icon: 'terminal'
  color: 'blue'
runs:
  using: 'node16'
  main: 'dist/index.js'
